### ISSUE TITLE
{"error":"an unknown error occured"}

### ISSUE THREAD

**Issue by alsak0de** [transparency-everywhere/ais-api#28]
Hiya, thanks for sharing your project. Not sure it is still alive, though.
If so, any clue on why all VF calls would return this error?

{"error":"an unknown error occured"}

The result seems to be perfectly crawled and parsed in docker console.

**Comment by niczem** [comment]
Hi there, thanks for sharing the issue!

Could you send more details for the request you are making so I can reproduce the error?

**Comment by alsa-kode** [comment]
Sorry I missed your quick reply until now. A simple call to the docker's end point: 
http://192.168.86.87:5000/getLastPositionFromVF/225416000

RETURNS:

{"error":"an unknown error occured"}

and if I use the MT end point:
http://192.168.86.87:5000/getLastPositionFromMT/225416000

this is what I get:
{"error":"missing needed position data"}

**Comment by niczem** [comment]
should be fixed with:
https://github.com/transparency-everywhere/ais-api/pull/24
