### ISSUE TITLE
Area Keywords

### ISSUE THREAD

**Issue by SarahDal** [transparency-everywhere/ais-api#29]
Is it possible to find a list of the area keywords?

**Comment by niczem** [comment]
Which area keywords do you mean?

**Comment by niczem** [comment]
This repo will be archived and all issues will be closed,
the future development will happen in [this repo](https://github.com/transparency-everywhere/position-api/) in which all the functions of this repo are available under the "legacy" paths. Please note that they will be removed to a more common structure in future version.

Still thank you for writing the issue and sorry for not having the time for answering it.
