### ISSUE TITLE
Scrape AIS-Data within an Area

### ISSUE THREAD

**Issue by niczem** [transparency-everywhere/ais-api#3]
- Add Template for third_party_vehicles (to seperate them form the "normal" vehicles)

- Create a service to track all ships within the SAR-Area (Start tracking within tunesian waters, stop it in Egypt)
https://www.marinetraffic.com/getData/get_data_json_4/z:6/X:17/Y:12/station:0

Its absolutely fine if we don't store the data within the positions couchdb but only in a sqlite instead so that we dont sync those huge amounts  of data all the time.

**Comment by datenpate** [comment]
I will take over the job.
