### ISSUE TITLE
[Query] What do users to with the position data?

### ISSUE THREAD

**Issue by SingingDwarf** [transparency-everywhere/ais-api#37]
Are you able to provide any suggestions as to what can be done with the position data?

Say I wanted to track the location of a particular ship into a database over time and report this on a map, do you have any suggestions as to what tool(s) could be used please?

What do users do with the data made available using this tool?

**Comment by niczem** [comment]
One example is this application:
https://rogermexico.bearblog.dev/microsoft-is-phoning-home-the-content-of-your-powerpoint-slides/

(see location service)
