### ISSUE TITLE
getLocationFromVF doesn't work

### ISSUE THREAD

**Issue by tetron432** [transparency-everywhere/ais-api#40]
I tried using going to [http://host:port/getLastPositionFromVF/211281610](http://localhost:5000/getLastPositionFromVF/211281610) (the example from index.js) but I get an error message. I do not think that the getLocationFromVF is working anymore.

**Comment by niczem** [comment]
This repo will be archived and all issues will be closed,
the future development will happen in [this repo](https://github.com/transparency-everywhere/position-api/) in which all the functions of this repo are available under the "legacy" paths. Please note that they will be removed to a more common structure in future version.

Still thank you for writing the issue and sorry for not having the time for answering it. Feel free to create a new issue in the new repo
