### ISSUE TITLE
vessel departure, destination and eta

### ISSUE THREAD

**Issue by adrianh87** [transparency-everywhere/ais-api#47]
It would be nice to have this info also if available on /getLastPosition/

**Comment by niczem** [comment]
This repo will be archived and all issues will be closed,
the future development will happen in [this repo](https://github.com/transparency-everywhere/position-api/) in which all the functions of this repo are available under the "legacy" paths. Please note that they will be removed to a more common structure in future version.

Still thank you for writing the issue and sorry for not having the time for answering it. Feel free to create a new issue in the new repo
